# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
addons:
  apt:
    packages:
    - libglu1-mesa-dev
env:
  global:
    - RGL_USE_NULL=TRUE

warnings_are_errors: true

stages:
  - name: pre-cache1
  - name: pre-cache2
  - name: test

jobs:
  include:
    - stage: pre-cache1
      before_install:
         - echo 'options(Ncpus = 2)' >> ~/.Rprofile
      install:
         - R -e 'install.packages(c("remotes", "rgl"))'
      script: true
    - stage: pre-cache2
      before_install:
         - echo 'options(Ncpus = 2)' >> ~/.Rprofile
      install:
         - R -e 'remotes::install_github("natverse/nat",dependencies = TRUE)'
      script: true
    - stage: test
      before_install:
         - echo 'options(Ncpus = 2)' >> ~/.Rprofile
after_success:
  - Rscript -e 'install.packages("covr")'
  - Rscript -e 'covr::coveralls()'
